"""enhance positions table add 28 fields

Revision ID: 5634fb9b8af9
Revises: cc753a52971c
Create Date: 2026-01-13 18:24:44.121580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5634fb9b8af9'
down_revision: Union[str, Sequence[str], None] = 'cc753a52971c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('session_id', sa.String(length=50), nullable=True))
    op.add_column('positions', sa.Column('signal_id', sa.String(length=50), nullable=True))
    op.add_column('positions', sa.Column('strategy_id', sa.String(length=50), nullable=True))
    op.add_column('positions', sa.Column('magic_number', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('positions', sa.Column('realized_pnl_usd', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('realized_profit_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('close_reason', sa.String(length=50), nullable=True))
    op.add_column('positions', sa.Column('exit_type', sa.String(length=20), nullable=True))
    op.add_column('positions', sa.Column('mae_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('mfe_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('quality_score', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('is_winner', sa.Boolean(), nullable=True))
    op.add_column('positions', sa.Column('holding_time_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('positions', sa.Column('max_profit_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('max_drawdown_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('signal_confidence', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('execution_duration_ms', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('positions', sa.Column('slippage_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('closing_slippage_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('entry_tags', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('positions', sa.Column('asset_class', sa.String(length=20), nullable=True))
    op.add_column('positions', sa.Column('entry_to_sl_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('entry_to_tp_pips', sa.Float(precision=2), nullable=False, server_default='0.0'))
    op.add_column('positions', sa.Column('breakeven_activated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('positions', sa.Column('trailing_activated', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('positions', 'entry_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('positions', 'stop_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('positions', 'take_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('positions', 'current_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('positions', 'close_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('positions', 'volume',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('positions', 'pip_size',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('positions', 'pip_value_per_lot',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('positions', 'current_profit_pips',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('positions', 'current_pnl_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('positions', 'risk_amount_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('positions', 'potential_profit_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('positions', 'confluence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.create_index('idx_position_quality', 'positions', ['quality_score'], unique=False)
    op.create_index('idx_position_session', 'positions', ['session_id'], unique=False)
    op.create_index('idx_position_strategy', 'positions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_positions_quality_score'), 'positions', ['quality_score'], unique=False)
    op.create_index(op.f('ix_positions_session_id'), 'positions', ['session_id'], unique=False)
    op.create_index(op.f('ix_positions_signal_id'), 'positions', ['signal_id'], unique=False)
    op.create_foreign_key(None, 'positions', 'trading_sessions', ['session_id'], ['session_id'], ondelete='SET NULL')
    op.alter_column('supply_demand_zones', 'high_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'low_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'entry_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('supply_demand_zones', 'strength',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'confluence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_accounts', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_accounts', 'equity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('trading_sessions', 'total_pnl_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'win_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'gross_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'gross_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'profit_factor',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'average_win',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'average_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'max_drawdown',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'max_drawdown_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'starting_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'ending_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'data_quality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_sessions', 'data_quality_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trading_sessions', 'ending_balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'starting_balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'max_drawdown_percentage',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'max_drawdown',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'average_loss',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'average_win',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'profit_factor',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'gross_loss',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'gross_profit',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'win_rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_sessions', 'total_pnl_usd',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trading_accounts', 'equity',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trading_accounts', 'balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'confluence_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'strength',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'entry_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('supply_demand_zones', 'low_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('supply_demand_zones', 'high_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_positions_signal_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_session_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_quality_score'), table_name='positions')
    op.drop_index('idx_position_strategy', table_name='positions')
    op.drop_index('idx_position_session', table_name='positions')
    op.drop_index('idx_position_quality', table_name='positions')
    op.alter_column('positions', 'confluence_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('positions', 'potential_profit_usd',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'risk_amount_usd',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'current_pnl_usd',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'current_profit_pips',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'pip_value_per_lot',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'pip_size',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'volume',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'close_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('positions', 'current_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('positions', 'take_profit',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'stop_loss',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('positions', 'entry_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('positions', 'trailing_activated')
    op.drop_column('positions', 'breakeven_activated')
    op.drop_column('positions', 'entry_to_tp_pips')
    op.drop_column('positions', 'entry_to_sl_pips')
    op.drop_column('positions', 'asset_class')
    op.drop_column('positions', 'entry_tags')
    op.drop_column('positions', 'closing_slippage_pips')
    op.drop_column('positions', 'slippage_pips')
    op.drop_column('positions', 'execution_duration_ms')
    op.drop_column('positions', 'signal_confidence')
    op.drop_column('positions', 'max_drawdown_pips')
    op.drop_column('positions', 'max_profit_pips')
    op.drop_column('positions', 'holding_time_seconds')
    op.drop_column('positions', 'is_winner')
    op.drop_column('positions', 'quality_score')
    op.drop_column('positions', 'mfe_pips')
    op.drop_column('positions', 'mae_pips')
    op.drop_column('positions', 'exit_type')
    op.drop_column('positions', 'close_reason')
    op.drop_column('positions', 'realized_profit_pips')
    op.drop_column('positions', 'realized_pnl_usd')
    op.drop_column('positions', 'comment')
    op.drop_column('positions', 'magic_number')
    op.drop_column('positions', 'strategy_id')
    op.drop_column('positions', 'signal_id')
    op.drop_column('positions', 'session_id')
    # ### end Alembic commands ###
