"""Initial migration - create all tables

Revision ID: a2192c549d7b
Revises:
Create Date: 2025-11-09 17:35:30.029748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2192c549d7b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "supply_demand_zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("zone_type", sa.String(length=20), nullable=False),
        sa.Column("high_price", sa.Float(precision=10), nullable=False),
        sa.Column("low_price", sa.Float(precision=10), nullable=False),
        sa.Column("entry_price", sa.Float(precision=10), nullable=True),
        sa.Column("strength", sa.Float(precision=2), nullable=True),
        sa.Column("confluence_score", sa.Float(precision=2), nullable=True),
        sa.Column("touched_count", sa.Integer(), nullable=True),
        sa.Column("volume_confirmed", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column("timeframe", sa.String(length=10), nullable=True),
        sa.Column("first_detected", sa.DateTime(), nullable=False),
        sa.Column("last_touched", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("trend_direction", sa.String(length=10), nullable=True),
        sa.Column("market_session", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_strength", "supply_demand_zones", ["strength"], unique=False)
    op.create_index("idx_symbol_type", "supply_demand_zones", ["symbol", "zone_type"], unique=False)
    op.create_index(op.f("ix_supply_demand_zones_id"), "supply_demand_zones", ["id"], unique=False)
    op.create_index(
        op.f("ix_supply_demand_zones_symbol"), "supply_demand_zones", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_supply_demand_zones_zone_id"), "supply_demand_zones", ["zone_id"], unique=True
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.Enum("BUY", "SELL", name="tradedirection"), nullable=False),
        sa.Column("entry_price", sa.Float(precision=10), nullable=False),
        sa.Column("stop_loss", sa.Float(precision=10), nullable=False),
        sa.Column("take_profit", sa.Float(precision=10), nullable=True),
        sa.Column("volume", sa.Float(precision=8), nullable=False),
        sa.Column("risk_amount", sa.Float(precision=2), nullable=False),
        sa.Column("potential_profit", sa.Float(precision=2), nullable=True),
        sa.Column("pip_size", sa.Float(precision=10), nullable=False),
        sa.Column("pip_value_per_lot", sa.Float(precision=4), nullable=False),
        sa.Column("current_price", sa.Float(precision=10), nullable=True),
        sa.Column("current_profit_pips", sa.Float(precision=4), nullable=True),
        sa.Column("current_pnl_usd", sa.Float(precision=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "OPEN", "EXECUTED", "CLOSED", "CANCELLED", name="tradestatus"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_price", sa.Float(precision=10), nullable=True),
        sa.Column("exit_price", sa.Float(precision=10), nullable=True),
        sa.Column("strategy_name", sa.String(length=100), nullable=True),
        sa.Column("confluence_score", sa.Float(precision=2), nullable=True),
        sa.Column("entry_zone_id", sa.Integer(), nullable=True),
        sa.Column("exit_zone_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("direction IN ('BUY', 'SELL')", name="check_direction"),
        sa.CheckConstraint("entry_price > 0", name="check_entry_price_positive"),
        sa.CheckConstraint("risk_amount > 0", name="check_risk_positive"),
        sa.CheckConstraint("stop_loss > 0", name="check_stop_loss_positive"),
        sa.CheckConstraint("volume > 0", name="check_volume_positive"),
        sa.ForeignKeyConstraint(
            ["entry_zone_id"],
            ["supply_demand_zones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exit_zone_id"],
            ["supply_demand_zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_opened_at", "trades", ["opened_at"], unique=False)
    op.create_index("idx_symbol_status", "trades", ["symbol", "status"], unique=False)
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    op.create_index(op.f("ix_trades_trade_id"), "trades", ["trade_id"], unique=True)
    op.create_table(
        "position_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column(
            "update_type",
            sa.Enum(
                "OPEN",
                "CLOSE",
                "MODIFY",
                "BREAKEVEN",
                "TRAILING_STOP",
                "PARTIAL_CLOSE",
                name="positionupdatetype",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("old_stop_loss", sa.Float(precision=10), nullable=True),
        sa.Column("old_take_profit", sa.Float(precision=10), nullable=True),
        sa.Column("old_volume", sa.Float(precision=8), nullable=True),
        sa.Column("new_stop_loss", sa.Float(precision=10), nullable=True),
        sa.Column("new_take_profit", sa.Float(precision=10), nullable=True),
        sa.Column("new_volume", sa.Float(precision=8), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "update_type IN ('OPEN', 'CLOSE', 'MODIFY', 'BREAKEVEN', 'TRAILING_STOP', 'PARTIAL_CLOSE')",
            name="check_update_type",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_timestamp", "position_updates", ["timestamp"], unique=False)
    op.create_index(
        "idx_trade_update_type", "position_updates", ["trade_id", "update_type"], unique=False
    )
    op.create_index(op.f("ix_position_updates_id"), "position_updates", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_updates_id"), table_name="position_updates", if_exists=True)
    op.drop_index(op.f("idx_trade_update_type"), table_name="position_updates", if_exists=True)
    op.drop_index(op.f("idx_timestamp"), table_name="position_updates", if_exists=True)
    op.drop_table("position_updates")
    op.drop_index(op.f("ix_trades_trade_id"), table_name="trades", if_exists=True)
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades", if_exists=True)
    op.drop_index(op.f("ix_trades_id"), table_name="trades", if_exists=True)
    op.drop_index(op.f("idx_symbol_status"), table_name="trades", if_exists=True)
    op.drop_index(op.f("idx_opened_at"), table_name="trades", if_exists=True)
    op.drop_table("trades")
    op.drop_index(
        op.f("ix_supply_demand_zones_zone_id"), table_name="supply_demand_zones", if_exists=True
    )
    op.drop_index(
        op.f("ix_supply_demand_zones_symbol"), table_name="supply_demand_zones", if_exists=True
    )
    op.drop_index(
        op.f("ix_supply_demand_zones_id"), table_name="supply_demand_zones", if_exists=True
    )
    op.drop_index(op.f("idx_symbol_type"), table_name="supply_demand_zones", if_exists=True)
    op.drop_index(op.f("idx_strength"), table_name="supply_demand_zones", if_exists=True)
    op.drop_table("supply_demand_zones")

    # Drop ENUM types manually (they are not automatically dropped)
    op.execute("DROP TYPE IF EXISTS tradedirection CASCADE")
    op.execute("DROP TYPE IF EXISTS positionupdatetype CASCADE")
    # ### end Alembic commands ###
