"""add_account_id_to_positions

Revision ID: c7944eb8482a
Revises: 0b9ebafd26aa
Create Date: 2026-01-13 16:50:43.712775

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7944eb8482a"
down_revision: str | Sequence[str] | None = "0b9ebafd26aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("account_id", sa.Integer(), nullable=True))
    op.alter_column(
        "positions",
        "entry_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "stop_loss",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "take_profit",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "close_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "volume",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_size",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_value_per_lot",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_profit_pips",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_pnl_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "risk_amount_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "potential_profit_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "confluence_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.create_index("idx_position_account", "positions", ["account_id"], unique=False)
    op.create_index(op.f("ix_positions_account_id"), "positions", ["account_id"], unique=False)
    op.create_foreign_key(
        None, "positions", "trading_accounts", ["account_id"], ["account_id"], ondelete="SET NULL"
    )
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "trading_accounts",
        "balance",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "trading_accounts",
        "equity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trading_accounts",
        "equity",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "trading_accounts",
        "balance",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "positions", type_="foreignkey")
    op.drop_index(op.f("ix_positions_account_id"), table_name="positions")
    op.drop_index("idx_position_account", table_name="positions")
    op.alter_column(
        "positions",
        "confluence_score",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "positions",
        "potential_profit_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "risk_amount_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_pnl_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_profit_pips",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_value_per_lot",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_size",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "volume",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "close_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "current_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "take_profit",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "stop_loss",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "entry_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("positions", "account_id")
    # ### end Alembic commands ###
