"""create trading accounts table

Revision ID: d50050150705
Revises: bb51ca8acdf0
Create Date: 2026-01-13 09:57:15.009071

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d50050150705"
down_revision: str | Sequence[str] | None = "bb51ca8acdf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("broker_name", sa.String(length=100), nullable=False),
        sa.Column("account_number", sa.String(length=50), nullable=False),
        sa.Column("account_type", sa.String(length=10), nullable=False),
        sa.Column("balance", sa.Float(precision=2), nullable=False),
        sa.Column("equity", sa.Float(precision=2), nullable=True),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("account_type IN ('DEMO', 'LIVE')", name="check_account_type_valid"),
        sa.CheckConstraint("balance >= 0", name="check_balance_positive"),
        sa.CheckConstraint("leverage >= 1 AND leverage <= 2000", name="check_leverage_range"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_account_active", "trading_accounts", ["is_active"], unique=False)
    op.create_index(
        "idx_account_broker", "trading_accounts", ["broker_name", "account_number"], unique=False
    )
    op.create_index(
        op.f("ix_trading_accounts_account_id"), "trading_accounts", ["account_id"], unique=True
    )
    op.create_index(op.f("ix_trading_accounts_id"), "trading_accounts", ["id"], unique=False)
    op.alter_column(
        "positions",
        "entry_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "stop_loss",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "take_profit",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "close_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "volume",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_size",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_value_per_lot",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_profit_pips",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_pnl_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "risk_amount_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "potential_profit_usd",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "confluence_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.drop_index(op.f("idx_position_ticket"), table_name="positions")
    op.create_index("idx_position_ticket", "positions", ["ticket"], unique=False)
    op.create_index(
        op.f("ix_positions_confluence_score"), "positions", ["confluence_score"], unique=False
    )
    op.create_index(op.f("ix_positions_ticket"), "positions", ["ticket"], unique=True)
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_positions_ticket"), table_name="positions")
    op.drop_index(op.f("ix_positions_confluence_score"), table_name="positions")
    op.drop_index("idx_position_ticket", table_name="positions")
    op.create_index(op.f("idx_position_ticket"), "positions", ["ticket"], unique=True)
    op.alter_column(
        "positions",
        "confluence_score",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "positions",
        "potential_profit_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "risk_amount_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_pnl_usd",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "current_profit_pips",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_value_per_lot",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "pip_size",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "volume",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "close_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "current_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "take_profit",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "stop_loss",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "positions",
        "entry_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_trading_accounts_id"), table_name="trading_accounts")
    op.drop_index(op.f("ix_trading_accounts_account_id"), table_name="trading_accounts")
    op.drop_index("idx_account_broker", table_name="trading_accounts")
    op.drop_index("idx_account_active", table_name="trading_accounts")
    op.drop_table("trading_accounts")
    # ### end Alembic commands ###
