"""create positions table

Revision ID: f5ee315d1247
Revises: a2192c549d7b
Create Date: 2025-12-06 18:55:24.088119

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5ee315d1247"
down_revision: Union[str, Sequence[str], None] = "a2192c549d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("position_type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entry_price", sa.Float(precision=10), nullable=False),
        sa.Column("stop_loss", sa.Float(precision=10), nullable=False),
        sa.Column("take_profit", sa.Float(precision=10), nullable=False),
        sa.Column("current_price", sa.Float(precision=10), nullable=True),
        sa.Column("close_price", sa.Float(precision=10), nullable=True),
        sa.Column("volume", sa.Float(precision=2), nullable=False),
        sa.Column("pip_size", sa.Float(precision=10), nullable=False),
        sa.Column("pip_value_per_lot", sa.Float(precision=10), nullable=False),
        sa.Column("current_profit_pips", sa.Float(precision=2), nullable=False),
        sa.Column("current_pnl_usd", sa.Float(precision=2), nullable=False),
        sa.Column("risk_amount_usd", sa.Float(precision=2), nullable=False),
        sa.Column("potential_profit_usd", sa.Float(precision=2), nullable=False),
        sa.Column("open_time", sa.DateTime(), nullable=True),
        sa.Column("close_time", sa.DateTime(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_index(op.f("ix_positions_position_id"), "positions", ["position_id"], unique=True)
    op.create_index(op.f("ix_positions_symbol"), "positions", ["symbol"], unique=False)
    op.drop_index(op.f("idx_timestamp"), table_name="position_updates")
    op.drop_index(op.f("idx_trade_update_type"), table_name="position_updates")
    op.drop_index(op.f("ix_position_updates_id"), table_name="position_updates")
    op.drop_table("position_updates")
    op.drop_index(op.f("idx_opened_at"), table_name="trades")
    op.drop_index(op.f("idx_symbol_status"), table_name="trades")
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades")
    op.drop_index(op.f("ix_trades_trade_id"), table_name="trades")
    op.drop_table("trades")
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=10),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        nullable=False,
    )
    op.alter_column(
        "supply_demand_zones", "touched_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "supply_demand_zones",
        "volume_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("supply_demand_zones", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "supply_demand_zones", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "supply_demand_zones", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supply_demand_zones", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "supply_demand_zones", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("supply_demand_zones", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "supply_demand_zones",
        "volume_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "supply_demand_zones", "touched_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "supply_demand_zones",
        "confluence_score",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "strength",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "entry_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "supply_demand_zones",
        "low_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "supply_demand_zones",
        "high_price",
        existing_type=sa.Float(precision=10),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.create_table(
        "trades",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('trades_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("trade_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "direction",
            postgresql.ENUM("BUY", "SELL", name="tradedirection"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("entry_price", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("stop_loss", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("take_profit", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("volume", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("risk_amount", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("potential_profit", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("pip_size", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("pip_value_per_lot", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("current_price", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("current_profit_pips", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("current_pnl_usd", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "OPEN", "EXECUTED", "CLOSED", "CANCELLED", name="tradestatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "opened_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "closed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("close_price", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("exit_price", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("strategy_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("confluence_score", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("entry_zone_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("exit_zone_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "direction = ANY (ARRAY['BUY'::tradedirection, 'SELL'::tradedirection])",
            name="check_direction",
        ),
        sa.CheckConstraint("entry_price > 0::double precision", name="check_entry_price_positive"),
        sa.CheckConstraint("risk_amount > 0::double precision", name="check_risk_positive"),
        sa.CheckConstraint("stop_loss > 0::double precision", name="check_stop_loss_positive"),
        sa.CheckConstraint("volume > 0::double precision", name="check_volume_positive"),
        sa.ForeignKeyConstraint(
            ["entry_zone_id"], ["supply_demand_zones.id"], name="trades_entry_zone_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["exit_zone_id"], ["supply_demand_zones.id"], name="trades_exit_zone_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="trades_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_trades_trade_id"), "trades", ["trade_id"], unique=True)
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_index(op.f("idx_symbol_status"), "trades", ["symbol", "status"], unique=False)
    op.create_index(op.f("idx_opened_at"), "trades", ["opened_at"], unique=False)
    op.create_table(
        "position_updates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("trade_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "update_type",
            postgresql.ENUM(
                "OPEN",
                "CLOSE",
                "MODIFY",
                "BREAKEVEN",
                "TRAILING_STOP",
                "PARTIAL_CLOSE",
                name="positionupdatetype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("old_stop_loss", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("old_take_profit", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("old_volume", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("new_stop_loss", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("new_take_profit", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("new_volume", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("triggered_by", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "update_type = ANY (ARRAY['OPEN'::positionupdatetype, 'CLOSE'::positionupdatetype, 'MODIFY'::positionupdatetype, 'BREAKEVEN'::positionupdatetype, 'TRAILING_STOP'::positionupdatetype, 'PARTIAL_CLOSE'::positionupdatetype])",
            name=op.f("check_update_type"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("position_updates_trade_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("position_updates_pkey")),
    )
    op.create_index(op.f("ix_position_updates_id"), "position_updates", ["id"], unique=False)
    op.create_index(
        op.f("idx_trade_update_type"), "position_updates", ["trade_id", "update_type"], unique=False
    )
    op.create_index(op.f("idx_timestamp"), "position_updates", ["timestamp"], unique=False)
    op.drop_index(op.f("ix_positions_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_position_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_table("positions")
    # ### end Alembic commands ###
