asset_classes:
  commodity:
  - XAUUSD
  - XAGUSD
  - WTIUSD
  - BRENTUSD
  crypto:
  - BTCUSD
  - ETHUSD
  - LTCUSD
  - BCHUSD
  - XRPUSD
  forex:
  - EURUSD
  - GBPUSD
  - USDJPY
  - USDCHF
  - AUDUSD
  - NZDUSD
  - USDCAD
  - EURGBP
  - EURJPY
  - GBPJPY
  - EURCHF
  - GBPCHF
  - AUDJPY
  - CADJPY
  - CHFJPY
  - NZDJPY
  - AUDCHF
  - CADCHF
  - NZDCHF
  - EURNZD
  - GBPNZD
  - AUDNZD
  - EURAUD
  - EURCAD
  - GBPAUD
  - GBPCAD
  index:
  - US30
  - SPX500
  - NAS100
  - UK100
  - GER40
  - JPN225
  - CHN50
brokers:
  admiral_markets:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  alpari:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  exness_cent:
    AUDUSD: AUDUSDc
    BTCUSD: BTCUSDc
    ETHUSD: ETHUSDc
    EURCHF: EURCHFc
    EURGBP: EURGBPc
    EURJPY: EURJPYc
    EURUSD: EURUSDc
    GBPCHF: GBPCHFc
    GBPJPY: GBPJPYc
    GBPUSD: GBPUSDc
    NZDUSD: NZDUSDc
    USDCAD: USDCADc
    USDCHF: USDCHFc
    USDJPY: USDJPYc
    XAGUSD: XAGUSDc
    XAUUSD: XAUUSDc
  exness_standard:
    AUDJPY: AUDJPYm
    AUDUSD: AUDUSDm
    BRENTUSD: BRENTUSDm
    BTCUSD: BTCUSDm
    CADJPY: CADJPYm
    CHFJPY: CHFJPYm
    ETHUSD: ETHUSDm
    EURCHF: EURCHFm
    EURGBP: EURGBPm
    EURJPY: EURJPYm
    EURUSD: EURUSDm
    GBPCHF: GBPCHFm
    GBPJPY: GBPJPYm
    GBPUSD: GBPUSDm
    LTCUSD: LTCUSDm
    NZDJPY: NZDJPYm
    NZDUSD: NZDUSDm
    USDCAD: USDCADm
    USDCHF: USDCHFm
    USDJPY: USDJPYm
    WTIUSD: WTIUSDm
    XAGUSD: XAGUSDm
    XAUUSD: XAUUSDm
  fxcm:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  fxpro:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  fxtm:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  ic_markets:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  instaforex:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  oanda:
    AUDUSD: AUD_USD
    BTCUSD: BTC_USD
    ETHUSD: ETH_USD
    EURCHF: EUR_CHF
    EURGBP: EUR_GBP
    EURJPY: EUR_JPY
    EURUSD: EUR_USD
    GBPCHF: GBP_CHF
    GBPJPY: GBP_JPY
    GBPUSD: GBP_USD
    NZDUSD: NZD_USD
    USDCAD: USD_CAD
    USDCHF: USD_CHF
    USDJPY: USD_JPY
    XAGUSD: XAG_USD
    XAUUSD: XAU_USD
  octafx:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  pepperstone:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  roboforex:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURUSD: EURUSD
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: XAGUSD
    XAUUSD: XAUUSD
  xm_cent:
    AUDUSD: AUDUSD.micro
    EURUSD: EURUSD.micro
    GBPUSD: GBPUSD.micro
    NZDUSD: NZDUSD.micro
    USDCAD: USDCAD.micro
    USDCHF: USDCHF.micro
    USDJPY: USDJPY.micro
    XAGUSD: SILVER.micro
    XAUUSD: GOLD.micro
  xm_standard:
    AUDUSD: AUDUSD
    BTCUSD: BTCUSD
    ETHUSD: ETHUSD
    EURCHF: EURCHF
    EURGBP: EURGBP
    EURJPY: EURJPY
    EURUSD: EURUSD
    GBPCHF: GBPCHF
    GBPJPY: GBPJPY
    GBPUSD: GBPUSD
    NZDUSD: NZDUSD
    USDCAD: USDCAD
    USDCHF: USDCHF
    USDJPY: USDJPY
    XAGUSD: SILVER
    XAUUSD: GOLD
default_broker: exness_cent
pip_values:
  commodities: 0.1
  crypto: 1.0
  forex_jpy: 0.01
  forex_major: 0.0001
pip_values_per_lot:
  commodities: 10.0
  crypto: 1.0
  forex_jpy: 9.09
  forex_major: 10.0
special_reverse_mappings:
  xm_cent:
    GOLD.micro: XAUUSD
    SILVER.micro: XAGUSD
  xm_standard:
    GOLD: XAUUSD
    SILVER: XAGUSD
